export enum EVENTS {
  NewUser = 'NewUser',
}

export enum APP {
  API_GATEWAY_SERVICE = 'API_GATEWAY_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
}

export enum AUTH_REQUESTS {
  GET_USERS = 'GET_USERS',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  POST_USERS = 'POST_USERS',
  PUT_USER_BY_ID = 'PUT_USER_BY_ID',
  DELETE_USER_BY_ID = 'DELETE_USER_BY_ID',
}